name: Auto Assign Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to creator
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: [context.payload.sender.login]
            })